// <auto-generated />
using System;
using AccessibleSchoolReports.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessibleSchoolReports.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchoolReportsDbContext))]
    partial class SchoolReportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.GraduateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empgen")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emptype1")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firm1")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobFtPt")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jobcat1")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jobreg")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jobst")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lfjob")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationFlag")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Minstat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalFtPerm")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolFund")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex3")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Time1")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("ImportRunId", "SchoolId");

                    b.ToTable("GraduateRecords", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ImportRowIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("ImportRunId", "RowNumber");

                    b.ToTable("ImportRowIssues", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlankRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvalidRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("StartedUtc");

                    b.ToTable("ImportRuns", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ReportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParallelism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.ToTable("ReportRuns", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ReportRunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportRunId");

                    b.HasIndex("SchoolId");

                    b.ToTable("ReportRunItems", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.GraduateRecord", b =>
                {
                    b.HasOne("AccessibleSchoolReports.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("Graduates")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessibleSchoolReports.Domain.Entities.School", "School")
                        .WithMany("Graduates")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRun");

                    b.Navigation("School");
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ImportRowIssue", b =>
                {
                    b.HasOne("AccessibleSchoolReports.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("Issues")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ReportRunItem", b =>
                {
                    b.HasOne("AccessibleSchoolReports.Domain.Entities.ReportRun", "ReportRun")
                        .WithMany("Items")
                        .HasForeignKey("ReportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessibleSchoolReports.Domain.Entities.School", "School")
                        .WithMany("ReportRunItems")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportRun");

                    b.Navigation("School");
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ImportRun", b =>
                {
                    b.Navigation("Graduates");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.ReportRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AccessibleSchoolReports.Domain.Entities.School", b =>
                {
                    b.Navigation("Graduates");

                    b.Navigation("ReportRunItems");
                });
#pragma warning restore 612, 618
        }
    }
}
