namespace AccessibleSchoolReports.Domain.Recodes;

/// <summary>
/// School names from live <c>%SCHRPTS(CODE, NAME, …)</c> calls in
/// <c>legacy/sas/schreptsummary_2025.sas</c> (SS-PREP-03 / SS-HDR-01).
/// Commented calls are omitted. Names are not invented.
/// </summary>
public static class LegacySchoolNames
{
    private static readonly Dictionary<string, string> Names = new(StringComparer.Ordinal)
    {
        ["10701"] = "Quinnipiac University School of Law",
        ["10702"] = "University of Connecticut School of Law",
        ["10703"] = "Yale Law School",
        ["12001"] = "University of Maine School of Law",
        ["12201"] = "Boston College Law School",
        ["12202"] = "Boston University School of Law",
        ["12203"] = "Harvard Law School",
        ["12204"] = "New England Law | Boston",
        ["12205"] = "Northeastern University School of Law",
        ["12206"] = "Suffolk University Law School",
        ["12207"] = "Western New England University School of Law",
        ["12208"] = "University of Massachusetts School of Law-Dartmouth",
        ["13001"] = "University of New Hampshire Franklin Pierce School of Law",
        ["14001"] = "Roger Williams University School of Law",
        ["14601"] = "Vermont Law School",
        ["23102"] = "Rutgers Law School",
        ["23103"] = "Seton Hall Law School",
        ["23301"] = "Albany Law School",
        ["23302"] = "Brooklyn Law School",
        ["23303"] = "Columbia Law School",
        ["23304"] = "Cornell Law School",
        ["23305"] = "Fordham University School of Law",
        ["23306"] = "Hofstra University Maurice A. Deane School of Law",
        ["23307"] = "University at Buffalo School of Law School",
        ["23308"] = "New York Law School",
        ["23309"] = "New York University School of Law",
        ["23310"] = "Elisabeth Haub School of Law at Pace University",
        ["23311"] = "St. Johns University School of Law",
        ["23312"] = "Syracuse University College of Law",
        ["23313"] = "Touro College - Jacob D. Fuchsberg Law Center",
        ["23314"] = "Benjamin N. Cardozo School of Law - Yeshiva University",
        ["23315"] = "City University of New York School of Law",
        ["23901"] = "Penn State Dickinson Law",
        ["23902"] = "Duquesne University Thomas R. Kline School of Law",
        ["23903"] = "University of Pennsylvania Carey Law School",
        ["23904"] = "University of Pittsburgh School of Law",
        ["23905"] = "Temple University - James E. Beasley School of Law",
        ["23906"] = "Villanova University Charles Widger School of Law",
        ["23907"] = "Drexel University Thomas R. Kline School of Law",
        ["23908"] = "Widener University Commonwealth Law School",
        ["31401"] = "The University of Chicago Law School",
        ["31402"] = "DePaul University College of Law",
        ["31403"] = "University of Illinois College of Law",
        ["31404"] = "Chicago-Kent College of Law - Illinois Institute of Technology",
        ["31405"] = "University of Illinois Chicago School of Law",
        ["31406"] = "Loyola University Chicago School of Law",
        ["31407"] = "Northern Illinois University College of Law",
        ["31408"] = "Northwestern Pritzker School of Law",
        ["31409"] = "Southern Illinois University Simmons Law School",
        ["31501"] = "Indiana University Maurer School of Law",
        ["31502"] = "Indiana University Robert H. McKinney School of Law",
        ["31503"] = "Notre Dame Law School",
        ["32301"] = "University of Detroit Mercy School of Law",
        ["32302"] = "Michigan State University College of Law",
        ["32303"] = "The University of Michigan Law School",
        ["32304"] = "Cooley Law School",
        ["32305"] = "Wayne State University Law School",
        ["33601"] = "The University of Akron School of Law",
        ["33602"] = "Capital University Law School",
        ["33603"] = "Case Western Reserve University School of Law",
        ["33604"] = "The University of Cincinnati Donald P. Klekamp College of Law",
        ["33605"] = "Cleveland State University College of Law",
        ["33606"] = "University of Dayton School of Law",
        ["33607"] = "Ohio Northern University Claude W. Pettit College of Law",
        ["33608"] = "The Ohio State University Moritz College of Law",
        ["33609"] = "University of Toledo College of Law",
        ["35001"] = "Marquette University Law School",
        ["35002"] = "University of Wisconsin Law School",
        ["41601"] = "Drake University Law School",
        ["41602"] = "University of Iowa College of Law",
        ["41701"] = "University of Kansas School of Law",
        ["41702"] = "Washburn University School of Law",
        ["42402"] = "University of Minnesota Law School",
        ["42403"] = "Mitchell Hamline School of Law",
        ["42404"] = "University of St. Thomas School of Law",
        ["42601"] = "University of Missouri School of Law",
        ["42602"] = "University of Missouri-Kansas City School of Law",
        ["42604"] = "Washington University School of Law",
        ["42801"] = "Creighton University School of Law",
        ["42802"] = "University of Nebraska College of Law",
        ["43501"] = "University of North Dakota School of Law",
        ["44201"] = "University of South Dakota School of Law",
        ["50801"] = "Widener University Delaware Law School",
        ["50901"] = "American University Washington College of Law",
        ["50903"] = "The Catholic University of America Columbus School of Law",
        ["50904"] = "Georgetown University Law Center",
        ["50905"] = "The George Washington University Law School",
        ["50906"] = "Howard University School of Law",
        ["50907"] = "University of the District of Columbia David A. Clarke School of Law",
        ["51001"] = "University of Florida - Fredric G. Levin College of Law",
        ["51002"] = "The Florida State University College of Law",
        ["51003"] = "University of Miami School of Law",
        ["51004"] = "Nova Southeastern University Shepard Broad College of Law",
        ["51005"] = "Stetson University College of Law",
        ["51006"] = "St. Thomas University College of Law",
        ["51007"] = "Florida Coastal School of Law",
        ["51008"] = "Barry University Dwayne O. Andreas School of Law",
        ["51009"] = "Florida Agricultural And Mechanical University College of Law",
        ["51010"] = "Florida International University College of Law",
        ["51011"] = "Ave Maria School of Law",
        ["51012"] = "Jacksonville University College of Law",
        ["51101"] = "Emory University School of Law",
        ["51102"] = "University of Georgia School of Law",
        ["51103"] = "Georgia State University College of Law",
        ["51104"] = "Mercer University School of Law",
        ["51105"] = "John Marshall Law School - Atlanta",
        ["51106"] = "Savannah Law School",
        ["52101"] = "University of Baltimore School of Law",
        ["52102"] = "University of Maryland Francis King Carey School of Law",
        ["53401"] = "Campbell University Norman A. Wiggins School of Law",
        ["53402"] = "Duke University School of Law",
        ["53403"] = "University of North Carolina School of Law",
        ["53405"] = "Wake Forest University School of Law",
        ["53407"] = "Elon University School of Law",
        ["54101"] = "University of South Carolina School of Law",
        ["54103"] = "Charleston School of Law",
        ["54701"] = "George Mason University Antonin Scalia Law School",
        ["54702"] = "University of Richmond School of Law",
        ["54704"] = "Washington and Lee University School of Law",
        ["54705"] = "William & Mary Law School",
        ["54706"] = "Regent University School of Law",
        ["54707"] = "Appalachian School of Law",
        ["54708"] = "Liberty University School of Law",
        ["54901"] = "West Virginia University College of Law",
        ["60101"] = "The University of Alabama School of Law",
        ["60102"] = "Samford University Cumberland School of Law",
        ["60103"] = "Faulkner University Thomas Goode Jones School of Law",
        ["61801"] = "University of Kentucky J. David Rosenberg College of Law",
        ["61802"] = "Louis D. Brandeis School of Law at the University of Louisville",
        ["61803"] = "Northern Kentucky University Salmon P. Chase College of Law",
        ["62501"] = "The University of Mississippi School of Law",
        ["62502"] = "Mississippi College School of Law",
        ["64301"] = "The University of Memphis Cecil C. Humphreys School of Law",
        ["64302"] = "University of Tennessee College of Law",
        ["64303"] = "Vanderbilt University Law School",
        ["64304"] = "Belmont University College of Law",
        ["64305"] = "Lincoln Memorial University Duncan School of Law",
        ["70401"] = "University of Arkansas School of Law",
        ["70402"] = "University of Arkansas at Little Rock William H. Bowen School of Law",
        ["71901"] = "Louisiana State University Paul M. Hebert Law Center",
        ["71902"] = "Loyola University New Orleans College of Law",
        ["71903"] = "Southern University Law Center",
        ["71904"] = "Tulane Law School",
        ["73701"] = "University of Oklahoma College of Law",
        ["73702"] = "Oklahoma City University School of Law",
        ["73704"] = "University of Tulsa College of Law",
        ["74401"] = "Baylor Law School",
        ["74402"] = "University of Houston Law Center",
        ["74403"] = "St. Marys University School of Law",
        ["74404"] = "SMU Dedman School of Law",
        ["74405"] = "South Texas College of Law Houston",
        ["74406"] = "The University of Texas School of Law",
        ["74407"] = "Texas Southern University - Thurgood Marshall School of Law",
        ["74408"] = "Texas Tech University School of Law",
        ["74409"] = "Texas A&M University School of Law",
        ["74410"] = "UNT Dallas College of Law",
        ["80301"] = "University of Arizona James E. Rogers College of Law",
        ["80302"] = "Sandra Day O Connor College of Law at Arizona State University",
        ["80601"] = "University of Colorado Law School",
        ["80602"] = "University of Denver Sturm College of Law",
        ["81301"] = "University of Idaho College of Law",
        ["82701"] = "Alexander Blewett III School of Law at the University of Montana",
        ["82901"] = "University of Nevada Las Vegas - William S. Boyd School of Law",
        ["83201"] = "University of New Mexico School of Law",
        ["84501"] = "Brigham Young University J. Reuben Clark Law School",
        ["84502"] = "University of Utah S.J. Quinney College of Law",
        ["85101"] = "University of Wyoming College of Law",
        ["90501"] = "University of California - Berkeley School of Law",
        ["90502"] = "University of California - Davis School of Law (King Hall)",
        ["90503"] = "UCLA School of Law",
        ["90504"] = "University of California College of the Law San Francisco",
        ["90505"] = "California Western School of Law",
        ["90507"] = "Loyola Law School",
        ["90508"] = "University of the Pacific - McGeorge School of Law",
        ["90509"] = "Pepperdine University Caruso School of Law",
        ["90510"] = "University of San Diego School of Law",
        ["90511"] = "University of San Francisco School of Law",
        ["90512"] = "Santa Clara University School of Law",
        ["90513"] = "University of Southern California Gould School of Law",
        ["90514"] = "Southwestern Law School",
        ["90515"] = "Stanford Law School",
        ["90518"] = "The Dale E. Fowler School of Law at Chapman University",
        ["90519"] = "Western State University College of Law",
        ["90520"] = "University of LaVerne College of Law",
        ["90521"] = "University of California - Irvine School of Law",
        ["91201"] = "University of Hawaii at Manoa William S. Richardson School of Law",
        ["93801"] = "Lewis & Clark Law School",
        ["93802"] = "University of Oregon School of Law",
        ["93803"] = "Willamette University College of Law",
        ["94801"] = "Gonzaga University School of Law",
        ["94802"] = "Seattle University School of Law",
        ["94803"] = "University of Washington School of Law",
    };

    public static IReadOnlyDictionary<string, string> All => Names;

    public static string? Lookup(string? code)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            return null;
        }

        return Names.TryGetValue(code.Trim(), out var name) ? name : null;
    }

    /// <summary>SAS name when the code is in %SCHRPTS; otherwise the stored name; otherwise the code.</summary>
    public static string Resolve(string? code, string? storedName = null)
    {
        if (Lookup(code) is { } sasName)
        {
            return sasName;
        }

        if (!string.IsNullOrWhiteSpace(storedName))
        {
            return storedName;
        }

        return string.IsNullOrWhiteSpace(code) ? string.Empty : code.Trim();
    }
}
